# Generated by Django 4.0.1 on 2022-01-09 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False, null=True)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_id', models.IntegerField(null=True)),
                ('district_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=50, null=True)),
                ('aadhar_no', models.CharField(max_length=12, null=True)),
                ('address', models.TextField()),
                ('csc_id', models.BooleanField(null=True)),
                ('csc_id_number', models.CharField(max_length=50, null=True)),
                ('bc_id', models.BooleanField(null=True)),
                ('bc_id_number', models.CharField(max_length=50, null=True)),
                ('csp_id', models.BooleanField(null=True)),
                ('csp_id_number', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('district_id', models.IntegerField(null=True)),
                ('state_id', models.IntegerField(null=True)),
                ('taluk_id', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('taluk', models.CharField(max_length=50, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('pan_number', models.CharField(max_length=50)),
                ('document_photo', models.FileField(null=True, upload_to='')),
                ('terms_condition', models.BooleanField(default=False)),
                ('form_verified', models.BooleanField(default=False, null=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_pe_number', models.CharField(max_length=20)),
                ('google_pay_number', models.CharField(max_length=20)),
                ('upi_id', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('qr_code', models.FileField(null=True, upload_to='')),
                ('state', models.CharField(max_length=100)),
                ('state_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boolean', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taluk_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_id', models.IntegerField(null=True)),
                ('district_id', models.IntegerField(null=True)),
                ('taluk_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('profile_photo', models.FileField(null=True, upload_to='')),
                ('role_id', models.IntegerField(null=True)),
                ('role', models.CharField(default='user', max_length=20, null=True)),
                ('otp', models.IntegerField(null=True)),
                ('otp_expiry', models.DateTimeField(null=True)),
                ('state_id', models.IntegerField(null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('taluk', models.CharField(max_length=50, null=True)),
                ('email_token', models.CharField(max_length=255, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('talukhead_id', models.IntegerField(null=True)),
                ('statehead_id', models.IntegerField(null=True)),
                ('designation_id', models.IntegerField(null=True)),
                ('districthead_id', models.IntegerField(null=True)),
                ('is_otpvalidated', models.BooleanField(default=False)),
                ('document_photo', models.FileField(null=True, upload_to='')),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('is_formupdated', models.BooleanField(default=False, null=True)),
                ('payment_photo', models.FileField(null=True, upload_to='')),
                ('is_paymentdone', models.BooleanField(default=False, null=True)),
                ('payment_verified', models.BooleanField(default=False, null=True)),
                ('approved_by', models.CharField(max_length=100, null=True)),
                ('form_verified', models.BooleanField(default=False, null=True)),
                ('is_Admin', models.BooleanField(default=False, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('assigned_stateid', models.IntegerField(null=True)),
                ('assigned_districtid', models.IntegerField(null=True)),
                ('assigned_talukid', models.IntegerField(null=True)),
                ('district_id', models.IntegerField(null=True)),
                ('state_updated', models.BooleanField(default=False, null=True)),
                ('taluk_id', models.IntegerField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
